# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"

# Title of your site
title = "Coding Club UC3M"

# Your copyright notice - appears in site footer.
# To display a copyright symbol, type `&copy;`.
copyright = 'Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>.'

theme = "hugo-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = "codingclubuc3m"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

# Get last modified date for content from Git?
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).
  extensions = ["backslashLineBreak"]

[params]
  # AUTHOR SETUP

  # Your details.
  name = "Coding Club UC3M"
  role = ""

  # Organizations/Affiliations.
  #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
  organizations = [ { name = "Universidad Carlos III de Madrid", url = "https://www.uc3m.es" } ]

  gravatar = true  # Get your avatar from Gravatar.com? (true/false)

  # Details for the Contact Widget
  email = "coding.club.uc3m@gmail.com"
  address = "Department of Statistics, UC3M, 28903 Getafe, Spain"
  #office_hours = ""
  #phone = "888 888 88 88"
  #skype = "echo123"
  #telegram = ""
  #keybase = ""

  # Enter an optional link for booking appointments (e.g. calendly.com).
  #appointment_url = ""

  # Discussion link (e.g. link to a forum, mailing list, or chat).
  #   Uncomment line below to use.
  #   discussion = { name = "Discuss", url = "https://discourse.gohugo.io" }

  # Enable/disable map in Contact widget.
  # To show your address on a map in the contact widget, you need to enter your latitude, longitude and choose
  # a map provider below.
  # To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `map = 2`.
  # To use OpenStreetMap on a high traffic site, set `map = 3` and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  # To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  map = 2
  map_api_key = ""
  latitude = "40.315080"
  longitude = "-3.725888"
  zoom = 15

  # SITE SETUP

  # Color theme.
  #   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`.
  color_theme = "ocean"
  # Enable users to switch between day and night mode?
  day_night = true

  # Font style.
  #   Choose from `default`, `classic`, or `playfair`.
  font = "default"

  # Description for social sharing and search engines. If undefined, author role is used in place.
  description = ""

  # Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
  sharing_image = ""

  # Twitter username (without @). Used when a vistor shares your site on Twitter.
  twitter = ""

  # Diplay a logo in navigation bar rather than title (optional).
  #   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
  logo = ""

  # Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "15:04"

  # Show estimated reading time for posts?
  reading_time = true

  # Display comment count? Requires commenting to be enabled.
  comment_count = true

  # Display next/previous section pager?
  section_pager = false

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = true

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   For the list of supported languages and styles, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = ["r", "julia"]
  # highlight_style = "github"

  # Enable native social sharing buttons?
  sharing = true

  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Configuration of talk pages.
  [params.talks]
    # Show talk time?
    time = true

  # Social/Academic Networking
  #
  # Icon pack "fab" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fas" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fontawesome.com/icons
  #
  # Icon pack "ai" includes the following academic icons:
  #
  #   cv, google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fas"
    link = "#contact"  # For a direct email link, use "mailto:test@example.org".

  [[params.social]]
    icon = "twitter"
    icon_pack = "fab"
    link = "https://twitter.com/CodingClubUC3M"

  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    link = "https://github.com/CodingClubUC3M"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[[menu.main]]
  name = "Sessions"
  url = "#talks"
  weight = 1

[[menu.main]]
  name = "About"
  url = "#about"
  weight = 2

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 3

[[menu.main]]
  name = '<span class="middot-divider"></span>'
  weight = 4

[[menu.main]]
  name = "Posts"
  url = "/post/"
  weight = 5

[[menu.main]]
  name = "Contributing"
  url = "/contribute/"
  weight = 6

# Search.
[params.search]
  # Search provider:
  #   0: No search engine
  #   1: Built-in (Fuse)
  #   2: Algolia (https://www.algolia.com)
  engine = 1

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [params.search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
